name: Feature request
description: Suggest a new feature or enhancement
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve beets-beatport4? Please describe it below.
        Check [existing issues](https://github.com/Samik081/beets-beatport4/issues?q=is%3Aissue+label%3Aenhancement) first to avoid duplicates.

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: What are you trying to accomplish? Why is the current behavior insufficient?
      placeholder: |
        When importing singleton tracks, I'd like the plugin to also fetch...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work? Include example config or behavior if possible.
      placeholder: |
        A new config option like:
        beatport4:
            new_option: yes
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds or alternative approaches?
    validations:
      required: false
